analyzer:
  errors:
    inference_failure_on_function_return_type: ignore
    parameter_assignments: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
